Remove the dockerlab VM
HOGENT-MLOps/mlops-labs pull request #60
Opened 2024-06-24 17:37 UTC by thomasaelbrecht

Closes #58

2024-08-16 21:22 UTC, MartenBE requested changes

2024-08-16 21:22 UTC, MartenBE commented on assignments/01-docker.md
> +- Linux: use [Docker Engine](https://docs.docker.com/engine/install/) and **not** Docker Desktop
Perhaps we can also advise them to use the package manager and just check if the version is up to date (or recent enough).

2024-08-16 21:22 UTC, MartenBE commented on assignments/01-docker.md
> +In a real-world scenario, you could bind the MySQL port (3306) to a port on your VM, but it's a bad idea to expose your database to the outside world. You should only allow traffic on the port of you
Remove the mention of a VM. Also, in a real-world scenario would actually be the scenario where this should not happen. I think we better rephrase here.

2024-08-17 11:44 UTC, thomasaelbrecht commented on assignments/01-docker.md
> +In a real-world scenario, you could bind the MySQL port (3306) to a port on your VM, but it's a bad idea to expose your database to the outside world. You should only allow traffic on the port of you
Something like this?

In a real-world scenario, it's a bad idea to expose your database to the outside world. You should only allow traffic from specific domains or IP addresses. You should block all other incoming traffic by using a firewall, but this is outside the scope of this course.

2024-08-17 11:46 UTC, thomasaelbrecht commented on assignments/01-docker.md
> +- Linux: use [Docker Engine](https://docs.docker.com/engine/install/) and **not** Docker Desktop
Should we mention the right commands or do they need to figure them out?

2024-08-21 11:05 UTC, thomasaelbrecht commented on assignments/01-docker.md
> +In a real-world scenario, you could bind the MySQL port (3306) to a port on your VM, but it's a bad idea to expose your database to the outside world. You should only allow traffic on the port of you
This is better:

In a real-world scenario, it's a bad idea to expose your database to the outside world. First think if public access is really necessary. If so, you should only allow traffic from specific domains or IP addresses. You should block all other incoming traffic by using a firewall, but this is outside the scope of this course.

2024-09-09 06:59 UTC, MartenBE commented on assignments/01-docker.md
> +- Linux: use [Docker Engine](https://docs.docker.com/engine/install/) and **not** Docker Desktop
Let them figure it out, but perhaps mention `apt`, `dnf`, `pacman`, ... and that they have to look it up according to their distro of choice. They should be able to handle that now, they've had Linux for Datascientists after all.

2024-09-09 07:20 UTC, thomasaelbrecht commented on assignments/01-docker.md
> +- Linux: use [Docker Engine](https://docs.docker.com/engine/install/) and **not** Docker Desktop
Isn't this already the case? Or should we remove the links for all OS'es?

2024-09-09 07:48 UTC, MartenBE commented on assignments/01-docker.md
> +- Linux: use [Docker Engine](https://docs.docker.com/engine/install/) and **not** Docker Desktop
Yes, but I would just also add the following:

> ... through a package manager (e.g. `apt`, `dnf`, `pacman`, ... depending on your distro). ...

2024-09-09 07:52 UTC, thomasaelbrecht commented on assignments/01-docker.md
> +- Linux: use [Docker Engine](https://docs.docker.com/engine/install/) and **not** Docker Desktop
https://github.com/HOGENT-MLOps/mlops-labs/blob/da1e8ed3fcb4bc098d9dfc2297a34dbc0d1e193f/assignments/01-docker.md?plain=1#L32

2024-09-09 07:53 UTC, MartenBE approved these changes

2024-09-09 07:53 UTC, merged