Add first draft for lab 3 using Prefect
HOGENT-MLOps/mlops-labs pull request #73
Opened 2024-09-14 15:21 UTC by thomasaelbrecht

This PR is not meant to be merged immediately. I just wanted to hear your feedback on this first draft.

Should we give them a very simple pipeline to demonstrate the working of `@task` and `@flow` or should the be able to do it all themselves? In the lab assignment you'll see that I just point to some documentation and that they need to develop the entire pipeline themselves.

We could also give the a base structure to plug the code into.

2024-09-16 10:33 UTC, MartenBE requested changes

2024-09-16 10:33 UTC, MartenBE commented on assignments/03-ml-workflow.md
>  - Show that you created an Azure ML workspace
Remove Azure

2024-09-16 10:33 UTC, MartenBE commented on assignments/03-ml-workflow.md
> +
If we handle python venv here, then it can be omitted from the monitoring lab.

2024-09-16 10:34 UTC, MartenBE commented
I think it is OK to let them try to figure it out for themselves. We just need to be really clear about the miminum requirements we want to see. If it proves to difficult, we can always give hints or explanation during class hours and adjust it for 2025-2026.

2024-09-17 15:20 UTC, thomasaelbrecht commented on assignments/03-ml-workflow.md
>  - Show that you created an Azure ML workspace
I'll remove these criteria when I have good alternatives for Prefect.

2024-09-18 10:26 UTC, thomasaelbrecht commented
Model deployment is now not present in the assignment, since we work locally. Optionally we can provide a Node.js server to try to perform a prediction?

2024-09-19 15:17 UTC, merged

2024-09-19 15:18 UTC, MartenBE commented
I have merged the PR, Adding the deployment could be nice, but if it is too much of a hassle, we could always leave it open as a possible extension