Fix/issue 81 82
HOGENT-MLOps/mlops-labs pull request #90
Opened 2024-10-28 17:36 UTC by thomasaelbrecht

2024-11-19 13:43 UTC, thomasaelbrecht commented
@MartenBE, don't you forget about these? 😇

2024-11-20 21:51 UTC, MartenBE requested changes

2024-11-20 21:51 UTC, MartenBE commented on assignments/01-docker.md
> +Do not use the root user for the database. Use the provided environment variables (by the [mysql](https://hub.docker.com/_/mysql) Docker image) to create a new user and database. Give the database a
Maybe add a `:warning:` icon?

2024-11-20 21:51 UTC, MartenBE commented on assignments/01-docker.md
> +> :question: Is it necessary to bind the MySQL port to the host system? Why (not)?
Good question :)!

2024-11-20 21:51 UTC, MartenBE commented on assignments/01-docker.md
>  > :warning: Docker Compose is now a plugin and should be used as `docker compose` and **not** `docker-compose`.
Maybe we should make this a hard requirement? A lot of students use ChatGPT or older youtube video's, blogposts, ... that uses the old `docker-compose` command. Perhaps we need to force their hand to use the new `docker compose` plugin.

2024-11-21 08:25 UTC, thomasaelbrecht commented on assignments/01-docker.md
> +> :question: Is it necessary to bind the MySQL port to the host system? Why (not)?
Yeah, I saw lots of port bindings for no reason. Some students even changed to port 3307 on their system because a local MySQL server was running.

2024-11-21 08:27 UTC, thomasaelbrecht commented on assignments/01-docker.md
>  > :warning: Docker Compose is now a plugin and should be used as `docker compose` and **not** `docker-compose`.
The thing is that `docker-compose` still works, at least on my Windows. We could indeed add an acceptance criterium for this, I'll make a proposal.

2024-11-21 13:01 UTC, MartenBE approved these changes

2024-11-21 13:02 UTC, merged